### ISSUE TITLE
Merge by other user won't start post receive hook

### ISSUE THREAD

**Issue by tcenl** [reconquest/atlassian-external-hooks#101]
Hello,

We are using Bitbucket 6.7.2 with External Hooks 7.5.0 and are encountering the problem that when we create a pull request on a repository with a post receive hook and an other users approves this (mandatory) and also merges it our post receive hook in not started. When we merge our own pull requests then it just works likes expected.

We get the following error in the atlassian-bitubcket.log:
```
2019-11-06 10:40:54,196 WARN  [AtlassianEvent::thread-3] [USER] @CHSM40x640x337x0 1ks2x81 127.0.0.1 "POST /rest/api/latest/projects/[PROJECT]/repos/[REPO]/pull-requests/26/merge HTTP/1.1" c.a.s.i.h.r.DefaultRepos
itoryHookService [[PROJECT]/[REPO][125]] Error calling ScriptRepositoryHook.postUpdate
com.atlassian.bitbucket.AuthorisationException: You are not permitted to access this resource
        at com.atlassian.stash.internal.aop.ExceptionRewriteAdvice.afterThrowing(ExceptionRewriteAdvice.java:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.atlassian.stash.internal.hook.script.DefaultHookScriptEnvironmentProvider.cloneUrls(DefaultHookScriptEnvironmentProvider.java:161)
        at com.atlassian.stash.internal.hook.script.DefaultHookScriptEnvironmentProvider.repoDetails(DefaultHookScriptEnvironmentProvider.java:198)
        at com.atlassian.stash.internal.hook.script.DefaultHookScriptEnvironmentProvider.mergeVariables(DefaultHookScriptEnvironmentProvider.java:173)
        at com.atlassian.stash.internal.hook.script.DefaultHookScriptEnvironmentProvider.create(DefaultHookScriptEnvironmentProvider.java:120)
        at com.atlassian.stash.internal.hook.script.DefaultHookScriptInvoker.lambda$prepareEnvironment$1(DefaultHookScriptInvoker.java:286)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at com.atlassian.stash.internal.hook.script.DefaultHookScriptInvoker.prepareEnvironment(DefaultHookScriptInvoker.java:287)
        at com.atlassian.stash.internal.hook.script.DefaultHookScriptInvoker.postUpdate(DefaultHookScriptInvoker.java:114)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.atlassian.stash.internal.plugin.OsgiSafeProxyProvider$1.invoke(OsgiSafeProxyProvider.java:95)
        at com.atlassian.stash.internal.hook.script.ScriptRepositoryHook.postUpdate(ScriptRepositoryHook.java:35)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.postUpdate(DefaultRepositoryHookService.java:760)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.lambda$doPostUpdate$7(DefaultRepositoryHookService.java:542)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.doPostUpdate(DefaultRepositoryHookService.java:526)
        at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.postUpdate(DefaultRepositoryHookService.java:329)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at jdk.internal.reflect.GeneratedMethodAccessor399.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.atlassian.stash.internal.hook.repository.CoreRefChangeEventToRepositoryHookAdapter.onRefsChanged(CoreRefChangeEventToRepositoryHookAdapter.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:42)
        at com.atlassian.diagnostics.internal.platform.event.EventSystemMonitor.invokeMonitored(EventSystemMonitor.java:109)
        at com.atlassian.diagnostics.internal.platform.event.MonitoredListenerInvoker.invoke(MonitoredListenerInvoker.java:38)
        at com.atlassian.stash.internal.event.AsyncBatchingInvokersTransformer$AsyncInvokerBatch.invoke(AsyncBatchingInvokersTransformer.java:111)
        at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.lambda$null$0(AsynchronousAbleEventDispatcher.java:37)
        at com.atlassian.sal.core.executor.ThreadLocalDelegateRunnable.run(ThreadLocalDelegateRunnable.java:34)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at com.atlassian.stash.internal.event.EventThreadFactory.lambda$createThread$0(EventThreadFactory.java:24)
        at java.base/java.lang.Thread.run(Thread.java:834)
        ... 37 frames trimmed
Caused by: org.springframework.security.access.AccessDeniedException: Access is denied
        at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
        ... 44 common frames omitted

```

**Comment by kovetskiy** [comment]
Hi,

Thanks for the report, we are investigating your report right now and trying to reproduce it. Although, the stacktrace doesn't contain our code and it looks like Bitbucket's internal issue with HookScripts, if it is true, we will escalate the issue to BB developers.

**Comment by tcenl** [comment]
Thanks for the reply! If we can help here in any way please let us know.

**Comment by seletskiy** [comment]
@tcenl: We were able to reproduce the problem using following scenario:

Two users:

* *User A*: read-only access to project;
* *User B*: admin access to project;

Scenario:

* Administrator enables repository-level *post*-receive hook script;

* *User A* forks repository;
* *User A* creates new branch, pushes some commits and creates pull request into project's repository;
* *User B* merges pull request;
* Post-receive hook script is not triggered and exception mentioned in the issue can be seen in logs.

*NOTE*: if *User A* will grant read-only access to his forked repo to *User B*, post-receive hook script is triggered succesfully

@bturner: it seems that it is a problem in the internal code of BB, could you confirm?

**Comment by tcenl** [comment]
@seletskiy Thanks for the quick reply! This is indeed the problem we have right now, the workaround also indeed works. 

Our production instance is Bitbucket 5.11.1 which works fine so I assume this is a problem introduced in a later version of Bitbucket. Currently we are checking if we have to postpone our upgrade of Bitbucket and wait untill it is fixed (by Atlassian if it's a BB bug).

**Comment by kovetskiy** [comment]
Yes, the addon on BB 6.X has completely different implementation due to
changes in Bitbucket API. We'd recommend postponing the upgrade of a major
version of BB if the case with fork & pr is frequent and important for you
till the issue is resolved.

**Comment by tcenl** [comment]
@kovetskiy Okay thank you for the information. Do we have to report this issue at Atlassian/Bitbucket or will you guys do this?

**Comment by kovetskiy** [comment]
@tcenl no worries, we will take care of it.

**Comment by kovetskiy** [comment]
@tcenl the Bitbucket Support has confirmed the bug and moved to the development team.

**Comment by tcenl** [comment]
@kovetskiy That's great to hear, thanks!

**Comment by bturner** [comment]
@kovetskiy @tcenl,

Thanks for the report. I've created [BSERV-12045](https://jira.atlassian.com/browse/BSERV-12045) to track a fix.

While the current behavior is unquestionably a bug, there's some complexity around how exactly it should be _fixed_. If the merging user doesn't have access to the source repository, they shouldn't be able to get clone URLs for it (which is what the system is doing when processing fails). On REST responses to the UI, for example, the merging user would not receive clone URLs as part of the JSON payload, and the UI would not attempt to link to the source repository. Of course, the other side of that is that there's a totally reasonable contention that, while hook scripts are invoked in the _context_ of a user, it's not that user invoking them--it's the system. I'm not sure how many hook scripts actually use the clone URL environment variables, so it's unclear what the impacts of either approach (omit URLs for repositories the user can't access, or always include URLs) would be.

Any thoughts?

Best regards,
Bryan Turner
Atlassian Bitbucket

**Comment by seletskiy** [comment]
@bturner my best guess is that most of hook implementations do not care much about clone URL of source repository as long as it has access to the changeset.

**Comment by kovetskiy** [comment]
@tcenl I see that you've also received JIRA email that BSERV-12045 was released, could you confirm that the bug is fixed for you?

**Comment by tcenl** [comment]
@kovetskiy I just updated our testing Bitbucket server and now it works fine again! Thanks for the quick help and support!

**Comment by seletskiy** [comment]
@tcenl: Thanks!

Feel free to reach us again if you will have any questions or problems.
