### ISSUE TITLE
"Can't get user email address" when receiving packets from "system accounts"

### ISSUE THREAD

**Issue by chburmeister** [reconquest/atlassian-external-hooks#60]
While monitoring our Bitbucket logs, we are facing a problem when the plugin tries to get the email adress of a "system account" that has only an access key to interact with Bitbucket:

/src/main/java/com/ngs/stash/externalhooks/hook/ExternalPreReceiveHook.java:
```
if (currentUser.getEmailAddress() != null) {
   env.put("STASH_USER_EMAIL", currentUser.getEmailAddress());
} else {
   log.error("Can't get user email address. getEmailAddress() call returns null");
}
```
OK, it cannot find an email adress as the committer is no real user with name/adress but is this really worth an error-loglevel? Is this STASH_USER_EMAIL information somewhere needed where it could be better logged as absent? By this logging, we got a log of false-positives.

**Comment by urol** [comment]
Bitbucket: 6.4.0
external-hooks-6.3.1-1

`
2019-07-17 14:53:44,926 WARN  [hook-callback:thread-2] 776d33e9299d2305 @1C1338Ox893x60707x1 v5bz8d 10.96.112.215 SSH - git-receive-pack '/dk/payment-gateway' c.a.s.i.h.r.DefaultRepositoryHookService [DK/payment-gateway[1280]] Error calling ScriptRepositoryHook.postUpdate
--
java.lang.NullPointerException: null value in entry: BB_USER_EMAIL=null
at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:176)
at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:285)
at com.atlassian.stash.internal.hook.script.DefaultHookScriptEnvironmentProvider.userDetails(DefaultHookScriptEnvironmentProvider.java:203)
at com.atlassian.stash.internal.hook.script.DefaultHookScriptEnvironmentProvider.create(DefaultHookScriptEnvironmentProvider.java:115)
at com.atlassian.stash.internal.hook.script.DefaultHookScriptInvoker.lambda$prepareEnvironment$1(DefaultHookScriptInvoker.java:286)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
at com.atlassian.stash.internal.hook.script.DefaultHookScriptInvoker.prepareEnvironment(DefaultHookScriptInvoker.java:287)
at com.atlassian.stash.internal.hook.script.DefaultHookScriptInvoker.postUpdate(DefaultHookScriptInvoker.java:114)
at com.atlassian.stash.internal.plugin.OsgiSafeProxyProvider$1.invoke(OsgiSafeProxyProvider.java:95)
at com.atlassian.stash.internal.hook.script.ScriptRepositoryHook.postUpdate(ScriptRepositoryHook.java:35)
at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.postUpdate(DefaultRepositoryHookService.java:760)
at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.lambda$doPostUpdate$7(DefaultRepositoryHookService.java:542)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.doPostUpdate(DefaultRepositoryHookService.java:526)
at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.postUpdateSynchronous(DefaultRepositoryHookService.java:336)
at com.atlassian.stash.internal.hook.DefaultBuiltInHookHandlerFactory.lambda$postReceive$1(DefaultBuiltInHookHandlerFactory.java:69)
at com.atlassian.stash.internal.hook.DefaultHookService.doHandleRequest(DefaultHookService.java:301)
at com.atlassian.stash.internal.hook.DefaultHookService.handleRequest(DefaultHookService.java:287)
at com.atlassian.stash.internal.hook.DefaultHookService.handleRawRequest(DefaultHookService.java:221)
at com.atlassian.stash.internal.hook.DefaultHookService$1.lambda$run$0(DefaultHookService.java:188)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.lang.Thread.run(Thread.java:748)
... 34 frames trimmed
`
Its just a WARN, but is it worth to print the stacktrace. It fills up the log approx 200 times a day in our case. The env var seems to be missing at this point in the case the user/mail comes from google groups via a UCS system.

**Comment by seletskiy** [comment]
@chburmeister @urol thanks for the bug reports. It will be fixed soon.

**Comment by bturner** [comment]
There seems to be 2 different manifestations of a similar issue under discussion here. The original description, from @chburmeister, is definitely not Bitbucket Server code. @urol’s error message is Bitbucket Server, though, definitely. Since e-mail addresses aren’t required (for example when Bitbucket Server is connected to an LDAP server), I agree there’s an issue there. For that case the hooks will completely fail to run; it’s not a “trivial” unnecessary warning message like the one from the description.

**Comment by bturner** [comment]
A fix for the Bitbucket Server issue is tracked at [BSERV-11869](https://jira.atlassian.com/browse/BSERV-11869).

**Comment by seletskiy** [comment]
@bturner Thank you, Bryan!
